Worker Inativar Usuário
prefeiturasp/SME-GoogleClassroom-API pull request #274
Opened 2021-07-12 03:04 UTC by rgalante82

AB#36775

2021-07-12 12:02 UTC, rafalosiamcom requested changes

2021-07-12 12:02 UTC, rafalosiamcom commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Usuarios/RepositorioUsuario.cs
> +                                            organization_path = 'Alunos>Inativos'
seria bom armazenar pelo menos a data_alteracao também para manter o controle de quando esse usuario foi inativado. Outra opção seria ter uma coluna com essa data.

2021-07-12 12:02 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Gsa/Sincronizacao/Usuarios/Inativacao/SincronizarInativacaoUsuarioGsaUseCase.cs
> +                var alunoInativado = await mediator.Send(new InativarUsuarioCommand(filtro.UsuarioId));
Esse command só troca o Path do registro na base GCA. Precisa enviar a inativação para o GSA também.

2021-07-13 18:36 UTC, rgalante82 commented on sme.gclass.api.worker.rabbit/RegistrarFilasRabbitMQ.cs
> +            if (consumoDeFilasOptions.Gsa.ProcessarInativacaoUsuarioGsa)
resolvido

2021-07-13 18:36 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Gsa/Sincronizacao/Usuarios/Inativacao/SincronizarInativacaoUsuarioGsaUseCase.cs
> +    public class SincronizarInativacaoUsuarioGsaUseCase : ISincronizarInativacaoUsuarioGsaUseCase
rotas criadas e registradas no worker

2021-07-13 18:37 UTC, rgalante82 commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Usuarios/RepositorioUsuario.cs
> +                                            organization_path = 'Alunos>Inativos'
criei um command para persistir as informações de usuarios inativos (UsuarioId, Data de Inativação e TipoUsuario)

2021-07-13 18:37 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Gsa/Sincronizacao/Usuarios/Inativacao/SincronizarInativacaoUsuarioGsaUseCase.cs
> +                var alunoInativado = await mediator.Send(new InativarUsuarioCommand(filtro.UsuarioId));
Sim, Esse Command faz apenas a atualização da Estrutura Organizacional!

2021-07-13 19:51 UTC, eliton-amcom commented on sme.gclass.api.dados/Interfaces/GoogleClassroom/IRepositorioCursoUsuario.cs
> +        Task<IEnumerable<CursoUsuarioInativarDto>> ObterUsuariosPorIdETurmaIdAsync(long usuarioId, long turmaId);
Não precisa mais colocar o nome de Async, por padrão todos as nossas consultas já são async

2021-07-14 23:12 UTC, rafalosiamcom requested changes

2021-07-14 23:12 UTC, rafalosiamcom commented on sme.gclass.api.dados/Repositorios/Eol/Usuarios/RepositorioAlunoEol.cs
> +											AND mte.cd_situacao_aluno IN (2,3,4,5,7,8,11,12,14,15)
esse cara estava errado na consulta de remoção de alunos do curso
```suggestion
											mte.cd_situacao_aluno IN (2,3,4,5,7,8,11,12,14,15)
```

2021-07-15 00:09 UTC, merged