Criação de script de controle de execução
prefeiturasp/SME-GoogleClassroom-API pull request #336
Opened 2021-07-23 18:05 UTC by rgalante82

AB#42916

2021-07-23 18:40 UTC, rafalosiamcom requested changes

2021-07-23 18:40 UTC, rafalosiamcom commented on scripts/V43__CONTROLE_EXECUCAO_ARQUIVAR_CURSOS_TURMAS_EXTINTAS.sql
> +select 15, '2021-01-01';
o 15 ja ta sendo usado na história Remover Professores

2021-07-23 18:59 UTC, rgalante82 commented on scripts/V43__CONTROLE_EXECUCAO_ARQUIVAR_CURSOS_TURMAS_EXTINTAS.sql
> +select 15, '2021-01-01';
Ajustado para 16

2021-07-26 12:46 UTC, rafalosiamcom approved these changes

2021-07-26 12:46 UTC, merged