Feature/49216
prefeiturasp/SME-GoogleClassroom-API pull request #423
Opened 2021-09-13 20:01 UTC by murilobarr0s

AB#49216

2021-09-13 20:13 UTC, rafalosiamcom requested changes

2021-09-13 20:13 UTC, rafalosiamcom commented on sme.gclass.api.worker.rabbit/Controllers/SincronizacaoGsaController.cs
> +            var retorno = await useCase.Executar(filtro);
no caso de retorno false não deve retornar 200, vai dar a impressão de que a carga foi iniciada e no tratamento de exceção na inclusão da carga esta retornando false

2021-09-13 20:13 UTC, rafalosiamcom commented on sme.gclass.api.infra/Fila/RotasRabbit.cs
> +        public static string FilaGsaCargaInicialManual => "googleclass.gsa.carga.inicial.manual.sync";
sugiro remover o "Manual" do atributo e rota

2021-09-13 20:35 UTC, murilobarr0s commented on sme.gclass.api.worker.rabbit/Controllers/SincronizacaoGsaController.cs
> +            var retorno = await useCase.Executar(filtro);
feito

2021-09-13 20:35 UTC, murilobarr0s commented on sme.gclass.api.infra/Fila/RotasRabbit.cs
> +        public static string FilaGsaCargaInicialManual => "googleclass.gsa.carga.inicial.manual.sync";
feito

2021-09-14 14:54 UTC, DiegoDigo commented on sme.gclass.application/Commands/CargaInicial/IncluirParametroCargaInicial/IncluirParametroCargaInicialCommandHandler.cs
> +namespace SME.GoogleClassroom.Aplicacao.Commands.CargaInicial.IncluirParametroCargaInicial
feito

2021-09-14 15:07 UTC, eliton-amcom approved these changes

2021-09-14 15:08 UTC, merged