Story/36781
prefeiturasp/SME-GoogleClassroom-API pull request #433
Opened 2021-09-20 13:08 UTC by eliton-amcom

AB#36781

2021-09-20 14:19 UTC, rafalosiamcom requested changes

2021-09-20 14:19 UTC, rafalosiamcom commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/CargaInicial/RepositorioCargaInicial.cs
> +                                            VALUES(@ano, @tiposUes, @ues, @turmas, @criadoEm) RETURNING ano;";
Não tem retorno
```suggestion
                                            VALUES(@ano, @tiposUes, @ues, @turmas, @criadoEm)";
```

2021-09-20 14:19 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Cursos/TrataSyncGoogleCursoUseCase.cs
>              var filtro = ObterFiltro(mensagemRabbit);
receber via mensagemRabbit um objeto do tipo "ParametrosCargaInicialDto".
Caso exista objeto recebido na mensagem utilizar ele senão ObterFiltro buscando os parametros da base.
Assim não faz a consulta na base desnecessariamente

2021-09-20 14:19 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Cursos/TrataSyncGoogleCursoUseCase.cs
> +            if (filtroCargaManual != null) ultimaExecucaoCursosIncluir = new DateTime(filtroCargaManual.AnoLetivo, 1, 1);
a regra deveria ser, data inicial = recebeu o filtro na mensagemRabbit ? 1/1/ano : ObterDataUltimaExecucaoPorTipoQuery

2021-09-20 14:19 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Cursos/TrataSyncGoogleCursoUseCase.cs
>              var filtro = ObterFiltro(mensagemRabbit);
Essa observação vale para todas as integrações

2021-09-20 18:26 UTC, eliton-amcom commented on sme.gclass.application/CasosDeUso/Cursos/TrataSyncGoogleCursoUseCase.cs
> +            if (filtroCargaManual != null) ultimaExecucaoCursosIncluir = new DateTime(filtroCargaManual.AnoLetivo, 1, 1);
corrigido

2021-09-20 18:26 UTC, eliton-amcom commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/CargaInicial/RepositorioCargaInicial.cs
> +                                            VALUES(@ano, @tiposUes, @ues, @turmas, @criadoEm) RETURNING ano;";
corrigido

2021-09-21 18:22 UTC, rafalosiamcom approved these changes

2021-09-21 18:22 UTC, merged