Feature/46901
prefeiturasp/SME-GoogleClassroom-API pull request #435
Opened 2021-09-23 11:49 UTC by rgalante82

AB#46901

2021-09-23 12:15 UTC, rafalosiamcom requested changes

2021-09-23 12:15 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +        }
Alterar validação de dono conforme instruido

2021-09-23 22:05 UTC, rafalosiamcom requested changes

2021-09-23 22:05 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +            var funcionariosDoCurso = await mediator.Send(new ObterFuncionariosPorCursoQuery(curso.Id));
essa carga não tem mais função

2021-09-23 22:05 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +            ehGestor = DonoDoCursoEhGestor(usuarioAtual, ehGestor);
o parametro ehGestor não tem função nesse método

2021-09-23 22:05 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +                var usuario = await mediator.Send(new ObterUsuarioGoogleQuery(professor.First().Email));
o unico atributo que esta sendo utilizado nesse objeto carregado é o Id e esse valor já tem no objeto professor então é desnecessário a carga novamente

2021-09-23 22:15 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +                    //await InserirProfessorCursoGoogleAsync(professor.First(), curso, existeProfessorCursoLocal);
ajustado

2021-09-23 22:16 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +            var funcionariosDoCurso = await mediator.Send(new ObterFuncionariosPorCursoQuery(curso.Id));
removido ObterFuncionariosPorCursoQuery

2021-09-23 22:17 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +            ehGestor = DonoDoCursoEhGestor(usuarioAtual, ehGestor);
retirei o parâmetro

2021-09-23 22:20 UTC, rgalante82 commented on sme.gclass.application/CasosDeUso/Usuarios/Professores/Cursos/InserirProfessorCursoGoogleUseCase.cs
> +                var usuario = await mediator.Send(new ObterUsuarioGoogleQuery(professor.First().Email));
Retirei a chamada para a consulta do usuário e estou pegando a informação do professor

2021-09-24 00:52 UTC, rafalosiamcom approved these changes

2021-09-24 00:52 UTC, merged