alterar importação de avisos
prefeiturasp/SME-GoogleClassroom-API pull request #455
Opened 2021-11-11 20:21 UTC by murilobarr0s

AB#46442

2021-11-11 20:31 UTC, rafalosiamcom requested changes

2021-11-11 20:31 UTC, rafalosiamcom commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Usuarios/Cursos/RepositorioCursoUsuario.cs
> +            sqlQuery.AppendLine("from cursos_gsa cg");
incluir o atributo de curso criado manualmente no retorno

2021-11-11 20:31 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Gsa/MuralAvisos/ImportarMuralAvisosCursoGsaUseCase.cs
> +                    bool criadoManualmente = await mediator.Send(new VerificaCursoCriadoManualmenteQuery(avisoGsa.CursoId));
utilizar o atributo já carregado da entidade curso_gsa ao invés de fazer uma nova consulta no banco

2021-11-11 20:31 UTC, rafalosiamcom commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Cursos/RepositorioCurso.cs
> +                            inner join public.cursos c on c.id = cast(cg.id as bigint)
essa consulta retorna os dados de CursoGoogle e não CursoGsaGoogle.
Não tem nenhum atributo novo da entidade curso_gsa então acredito que não precise alterar esse método

2021-11-12 14:01 UTC, murilobarr0s commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Cursos/RepositorioCurso.cs
> +                            inner join public.cursos c on c.id = cast(cg.id as bigint)
ajustado

2021-11-12 14:01 UTC, murilobarr0s commented on sme.gclass.application/CasosDeUso/Gsa/MuralAvisos/ImportarMuralAvisosCursoGsaUseCase.cs
> +                    bool criadoManualmente = await mediator.Send(new VerificaCursoCriadoManualmenteQuery(avisoGsa.CursoId));
ajustado

2021-11-12 14:02 UTC, murilobarr0s commented on sme.gclass.api.dados/Repositorios/GoogleClassroom/Usuarios/Cursos/RepositorioCursoUsuario.cs
> +            sqlQuery.AppendLine("from cursos_gsa cg");
ajustado

2021-11-12 14:02 UTC, merged