GCA - story/85760 --> MASTER
prefeiturasp/SME-GoogleClassroom-API pull request #588
Opened 2023-02-13 11:46 UTC by viniciusnyari

AB#85760
AB#85543

2023-02-16 15:56 UTC, rafalosiamcom requested changes

2023-02-16 15:56 UTC, rafalosiamcom commented on sme.gclass.application/CasosDeUso/Sga/FuncionariosProfessores/FuncionariosProfessoresEolSgaUseCase.cs
>          public FuncionariosProfessoresEolSgaUseCase(IMediator mediator)
Não deveriamos esta usando SGA nas classes e rotas no nosso sistema, pois afinal estamos retornando dados do EOL

2023-02-17 01:29 UTC, amcomsme commented on sme.gclass.application/CasosDeUso/Sga/FuncionariosProfessores/FuncionariosProfessoresEolSgaUseCase.cs
>          public FuncionariosProfessoresEolSgaUseCase(IMediator mediator)
Ajustado

2023-02-17 01:30 UTC, amcomsme commented on sme.gclass.application/CasosDeUso/Sga/FuncionariosProfessores/FuncionariosProfessoresEolSgaUseCase.cs
>          public FuncionariosProfessoresEolSgaUseCase(IMediator mediator)
Ajustado

2023-02-17 01:31 UTC, viniciusnyari commented on sme.gclass.application/CasosDeUso/Sga/FuncionariosProfessores/FuncionariosProfessoresEolSgaUseCase.cs
>          public FuncionariosProfessoresEolSgaUseCase(IMediator mediator)
Ajustado

2023-02-17 14:18 UTC, rafalosiamcom approved these changes

2023-02-17 14:19 UTC, merged